---
author: "Harrison Anthony"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
params:
  sample_id: ""
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,message=FALSE,dev='png',dpi=300)
```



```{r libs-and-functions}

#load libs
library(Seurat)
library(RColorBrewer)
library(gridExtra)
library(patchwork)
library(tidyverse)
library(scAnnotatR)
library(data.table)
library(cowplot)
library(Nebulosa)
library(ggpubr)
library(R.utils)
library(kableExtra)
library(gtools)


#set seed
set.seed(seed = 152727)

#anova boxplot function

box_plot <- function(patient,tukey_try){
#create boxplot for data vizz

patient_df <- filter(final_df, patient_id == patient) 

patient_df$cluster <- as.character(patient_df$cluster)

anova_result <- aov(msi_score ~ cluster,data = patient_df)
f_statistic <- round(summary(anova_result)[[1]][["F value"]][1],2)



tukey_result <- TukeyHSD(anova_result)
tukey_summary <- as.data.frame(tukey_result$cluster)

#find all cluster pairwise comparisons
x=as.character(c(0:max(patient_df$cluster)))



# Extract significant comparisons (p-value < 0.05)
significant_comparisons <- rownames(tukey_summary)[tukey_summary$`p adj` < 0.005]

comparisons <- str_split(significant_comparisons,pattern = '-')
p_values <- tukey_summary$`p adj`[tukey_summary$`p adj` < 0.005]
#annotations = signif(p_values, digits = 2)
annotations <- stars.pval(p_values)



bp <- ggplot(patient_df,aes(x=cluster,y=msi_score))+
  geom_boxplot(fill='lightblue',color='black')+
  labs(title=paste0(patient,' (F=',f_statistic,')'),x='Cluster',y='MSI score')+theme_minimal()



if(length(annotations)>0 & tukey_try==TRUE){
bp <- bp+ geom_signif(
  comparisons = comparisons,
  annotations = annotations,step_increase = 0.05,
  map_signif_level = TRUE,tip_length=.001,size = 0.001
)}
return((bp))

}

tukey_plot <- function(patient){
#create boxplot for data vizz

patient_df <- filter(final_df, patient_id == patient) 

patient_df$cluster <- as.character(patient_df$cluster)

anova_result <- aov(msi_score ~ cluster,data = patient_df)
f_statistic <- round(summary(anova_result)[[1]][["F value"]][1],2)



tukey_result <- TukeyHSD(anova_result)
plot(tukey_result,las=1,col = ifelse(tukey_result$cluster[,4]<0.05,'red','black'))

return((plot))

}





```

```{r handle-args}

args <- params$sample_id
sample_id <- args[1]

```

---
title: `r sample_id`
---







```{r read-in-data}

key <- fread('../manifests/combined_key.tsv')
#key <- filter(key, msi_status=='MSI-H')
treatment_meta_data <- fread('../manifests/final_gsm_key2.tsv')
key$treatment <- NA
for(i in 1:nrow(key)){
  if(key$patient_id[i] %in% treatment_meta_data$patient_id){
    treatment <- filter(treatment_meta_data, patient_id == key$patient_id[i]) %>% select('treatment')
    key$treatment[i]<- treatment
  }
}


patient=sample_id

sample_info <- filter(key, patient_id == patient )
if(! file.exists(paste0('../integrated_samples/',patient,'.rds')) | 
  ! file.exists(paste0('../integrated_samples/',patient,'_cancer.rds'))
){stop("missing integrated samples")} else{
 
if(nrow(sample_info) == 0){
  sample_info <- data.frame(patient_id = sample,
                            site ='tumor',
                            filename = sample,
                            msi_status = 'MSI-H',
                            msi_test='IHC/PCR')
} 
}
assign(x = 's_obj',value = readRDS(paste0('../integrated_samples/',patient,'.rds'))) 
assign(x = 's_obj_cancer',value = readRDS(paste0('../integrated_samples/',patient,'_cancer.rds')))

  
  



#create centroid info for num of cells labelling
cluster_counts <- table(Idents(s_obj))
s_obj$cluster_counts <- s_obj$seurat_clusters
temp <- as.numeric(levels(s_obj$cluster_counts))[s_obj$cluster_counts]
z=0
for(i in 1:length(cluster_counts)){
temp[temp == z]  <- paste0('n= ',as.numeric(cluster_counts[i]))
 z=z+1 
}
s_obj$cluster_counts <- temp

#quickly add pseuduobulk data
pseudobulk_status <- fread(paste0('../sensor_rna_results/int_',patient,'.txt'))
pseudobulk_status$sample_id <- gsub(pattern = 'g',replacement = '',x = pseudobulk_status$sample_id)
s_obj$pseudobulk_msi <- NA
cluster_key <- data.frame(cells=colnames(s_obj),cluster=s_obj$seurat_clusters)

for(i in 1:length(s_obj$pseudobulk_msi)){
  cell <- cluster_key$cells[i]
  cluster <- cluster_key$cluster[i]
  temp <- filter(pseudobulk_status, sample_id == as.numeric(as.character(cluster)))
  if(nrow(temp)==0){next}
  s_obj$pseudobulk_msi[i] <- temp$`probability_of_MSI-H`
  
  
}
#quickly add pseuduobulk data cancer
pseudobulk_status_cancer <- fread(paste0('../sensor_rna_results/int_',patient,'_cancer.txt'))
pseudobulk_status_cancer$sample_id <- gsub(pattern = 'g',replacement = '',x = pseudobulk_status_cancer$sample_id)
s_obj_cancer$pseudobulk_msi <- NA
cluster_key_cancer <- data.frame(cells=colnames(s_obj_cancer),cluster=s_obj_cancer$seurat_clusters)

for(i in 1:length(s_obj_cancer$pseudobulk_msi)){
  cell <- cluster_key_cancer$cells[i]
  cluster <- cluster_key_cancer$cluster[i]
  temp <- filter(pseudobulk_status_cancer, sample_id == as.numeric(as.character(cluster)))
 if(nrow(temp)==0){next}
  s_obj_cancer$pseudobulk_msi[i] <- temp$`probability_of_MSI-H`
  
  
}


#final df needed to plot tukey and anova
final_df <- data.frame(patient_id=patient,
                      cluster=s_obj_cancer$seurat_clusters,
                      msi_score=s_obj_cancer$sensor_rna_prob,
                      status=s_obj_cancer$sensor_rna_status)
final_df$cluster <- as.numeric(as.character(final_df$cluster))




```

```{r plotting,results='hide',fig.keep='all'}

myPalette <- colorRampPalette(rev(brewer.pal(11, "Spectral")))
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(0,1))
sc2 <- scale_colour_gradientn(colours = myPalette(100), limits=c(0,10))







p1 <- FeaturePlot(s_obj,features=c('sensor_rna_prob')) +
 ggtitle('Sensor RNA score')+sc
p2 <- FeaturePlot(s_obj,features=c("percent_msi"))+
  ggtitle('Percent of cells MSI-H')+sc2
p3 <- FeaturePlot(s_obj,features=c("pseudobulk_msi"))+
  ggtitle('Pseudobulk sensor RNA score')+sc

cancer_prob <- FeaturePlot(s_obj_cancer,features=c("sensor_rna_prob"),label = TRUE)+
  ggtitle('Recluster of cancer cells')+sc
cancer_pseudobulk <- FeaturePlot(s_obj_cancer,features=c("pseudobulk_msi"))+
  ggtitle('Cancer cells pseudobulk')+sc

cancer_percent <- FeaturePlot(s_obj_cancer,features=c("percent_msi"))+
  ggtitle('Percent of cells MSI-H')+sc2
cancer_tissue <- DimPlot(s_obj_cancer,group.by ='tissue')+ggtitle('Tissue contribution')



cell_types <- DimPlot(s_obj, group.by = "pan_cancer_cluster",cols=c("red","blue"))+ ggtitle("Simplified cell types")+
labs(fill="cell types")+
guides(colour = guide_legend(override.aes = list(size=1.6),ncol=1))+ 
  theme(legend.text=element_text(size=7))




kable_styling(kable(sample_info))

grid.arrange(cell_types,p1,ncol=2,nrow=1)
grid.arrange(p2,p3,ncol=2,nrow=1)
#top = textGrob("Daily QC: Blue",gp=gpar(fontsize=20,font=3)))
grid.arrange(cancer_prob,cancer_pseudobulk,cancer_percent,cancer_tissue,ncol=2)


#differentially expressed cancer clusters
de_cancer <- FindAllMarkers(s_obj_cancer,only.pos = FALSE) %>% filter(p_val_adj < 0.01)

#look at top 5 differentially expressed
top5 = matrix(ncol=7)
colnames(top5) = colnames(de_cancer)
for(i in 0:(length(levels(factor(s_obj_cancer$seurat_clusters)))-1)){
top5 = rbind(top5, head(de_cancer[which(de_cancer$cluster==i),], 5))
}

if(nrow(top5) < 2){
print('too few significantly, differentially expressed genes in integrated data for meaningful analysis')
}else{

top5=top5[-1,]



heatmap1 <- DoHeatmap(s_obj_cancer,features = top5$gene)
}

#find differentially expressed genes between msi-h and mss cells
Idents(s_obj_cancer) <- s_obj_cancer$sensor_rna_status

diff_genes <- FindAllMarkers(s_obj_cancer,only.pos = FALSE) %>% filter(p_val_adj < 0.01) %>% head(50)
if(nrow(diff_genes)<1){
print('no differentially expressed genes in cancer recluster file or between MSS/MSI-H cells')
print(heatmap1)
print(box_plot(patient,tukey_try=FALSE))
print(tukey_plot(patient))
} else if(length(diff_genes$gene[diff_genes$gene %in% rownames(s_obj_cancer@assays$RNA$scale.data)]) < 1){
print('possible conflict with scale data names and differentiall expressed annotation')
print(heatmap1)
} else{
print(heatmap1)
heatmap2 <- DoHeatmap(s_obj_cancer,features = diff_genes$gene,label = FALSE)
print(heatmap2)
print(box_plot(patient,tukey_try=FALSE))
print(tukey_plot(patient))
}




```






