---
title: "SC-ANOVA"
author: "Harrison Anthony"
date: "2024-12-16"
output:
  pdf_document: default
  html_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,message=FALSE,dev='png',dpi=300)
```
```{r libs-and-functions}

#load libs
library(Seurat)
library(RColorBrewer)
library(gridExtra)
library(patchwork)
library(tidyverse)
library(scAnnotatR)
library(data.table)
library(cowplot)
library(Nebulosa)
library(ggpubr)
library(R.utils)
library(kableExtra)
library(gtools)


#set seed
set.seed(seed = 152727)


```

```{r handle-data}
#prep key
key <- fread('C:/Users/Harrison Anthony/Desktop/git_repos/sc_msi/manifests/combined_key.tsv')
key <- filter(key, msi_status=='MSI-H')
patients <- unique(key$patient_id)

final_df <- data.frame()


for(patient in patients){
sample_info <- filter(key, patient_id == patient )
if(! file.exists(paste0('E:/temp/newest_dir/',patient,'.rds')) | 
  ! file.exists(paste0('E:/temp/newest_dir/',patient,'_cancer.rds')) |
  patient == "P21"){next} else{
 
if(nrow(sample_info) == 0){
  sample_info <- data.frame(patient_id = sample,
                            site ='tumor',
                            filename = sample,
                            msi_status = 'MSI-H',
                            msi_test='IHC/PCR')
} 
  }


  
  
  
  
  
  
treatment_meta_data <- fread('C:/Users/Harrison Anthony/Desktop/git_repos/sc_msi/manifests/final_gsm_key2.tsv')
key$treatment <- NA
for(i in 1:nrow(key)){
  if(key$patient_id[i] %in% treatment_meta_data$patient_id){
    treatment <- filter(treatment_meta_data, patient_id == key$patient_id[i]) %>% select('treatment')
    key$treatment[i]<- treatment
  }
}

#start with just one patient

assign(x = 's_obj_cancer',value = readRDS(paste0('E:/temp/newest_dir/',patient,'_cancer.rds')))


#quickly add pseuduobulk data cancer
pseudobulk_status_cancer <- fread(paste0('C:/Users/Harrison Anthony/Desktop/git_repos/sc_msi/sensor_rna_results/',patient,'_cancer.txt'))
pseudobulk_status_cancer$sample_id <- gsub(pattern = 'g',replacement = '',x = pseudobulk_status_cancer$sample_id)
s_obj_cancer$pseudobulk_msi <- NA
cluster_key_cancer <- data.frame(cells=colnames(s_obj_cancer),cluster=s_obj_cancer$seurat_clusters)

for(i in 1:length(s_obj_cancer$pseudobulk_msi)){
  cell <- cluster_key_cancer$cells[i]
  cluster <- cluster_key_cancer$cluster[i]
  temp <- filter(pseudobulk_status_cancer, sample_id == as.numeric(as.character(cluster)))
 if(nrow(temp)==0){next}
  s_obj_cancer$pseudobulk_msi[i] <- temp$`probability_of_MSI-H`
  
  
}

temp_data <- data.frame(patient_id=patient,
                      cluster=s_obj_cancer$seurat_clusters,
                      msi_score=s_obj_cancer$sensor_rna_prob,
                      status=s_obj_cancer$sensor_rna_status)
final_df <- rbind(final_df,temp_data)

}

final_df$cluster <- as.numeric(as.character(final_df$cluster))







```
```{r plotter}

bp_n_tukey <- function(patient,tukey_try){
#create boxplot for data vizz

patient_df <- filter(final_df, patient_id == patient) 

patient_df$cluster <- as.character(patient_df$cluster)

anova_result <- aov(msi_score ~ cluster,data = patient_df)
f_statistic <- round(summary(anova_result)[[1]][["F value"]][1],2)



tukey_result <- TukeyHSD(anova_result)
tukey_summary <- as.data.frame(tukey_result$cluster)

#find all cluster pairwise comparisons
x=as.character(c(0:max(patient_df$cluster)))



# Extract significant comparisons (p-value < 0.05)
significant_comparisons <- rownames(tukey_summary)[tukey_summary$`p adj` < 0.005]

comparisons <- str_split(significant_comparisons,pattern = '-')
p_values <- tukey_summary$`p adj`[tukey_summary$`p adj` < 0.005]
#annotations = signif(p_values, digits = 2)
annotations <- stars.pval(p_values)



bp <- ggplot(patient_df,aes(x=cluster,y=msi_score))+
  geom_boxplot(fill='lightblue',color='black')+
  labs(title=paste0(patient,' (F=',f_statistic,')'),x='Cluster',y='MSI score')+theme_minimal()



if(length(annotations)>0 & tukey_try==TRUE){
bp <- bp+ geom_signif(
  comparisons = comparisons,
  annotations = annotations,step_increase = 0.05,
  map_signif_level = TRUE,tip_length=.001,size = 0.001
)}
return((bp))

}

plot_list <- suppressWarnings(lapply(unique(final_df$patient_id),bp_n_tukey,tukey_try=FALSE))
plot_list2 <- suppressWarnings(lapply(unique(final_df$patient_id),bp_n_tukey,tukey_try=TRUE))

ggarrange(plotlist = plot_list,ncol = 3)
ggarrange(plotlist = plotlist2,ncol=3)


#question: is the MSI-score different between the cancer clusters



```
