# Config file for SC-MSI Snakemake file

# edit the following parameters below. Note the curent sample list must consist of matrix (mtx) files.

#specify list of sample names
sample_list: "../manifests/all_artificial_samples.tsv"

#reference transcriptome
transcriptome: "/data3/hanthony/reference_files/refdata-gex-GRCh38-2020-A"

#give key file
key: "../manifests/mixing_table_manifest.tsv"

